nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc_G.Velocity = Vector3.new(35, 0, 0)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc--VvdgKaeTwm Function--
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltclocal function VvdgKaeTwm(P0,P1,Position,Rotate)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	local VvdgKaeTwmPosition = Instance.new("WmfyUoPmvY", P0)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	local VvdgKaeTwmOrientation = Instance.new("pAcleKIwoU", P0)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	local MMDcYxstSC = Instance.new("Attachment", P0)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	local KleSOdxfiL = Instance.new("Attachment", P1)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	--Attach setup--
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	VvdgKaeTwmPosition.Attachment0,WmfyUoPmvY.MMDcYxstSC = Attachment1,KleSOdxfiL
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	VvdgKaeTwmOrientation.MaxTorque,pAcleKIwoU.Responsiveness = 9e9,200
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	--Properties/Config--
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	VvdgKaeTwmPosition.RigidityEnabled = true
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	VvdgKaeTwmOrientation.RigidityEnabled = true
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	--Rotate/Position
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	MMDcYxstSC.Position = Position or Vector3.new(0, 0, 0)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	MMDcYxstSC.Rotation = Rotate or Vector3.new(0, 0, 0)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcend
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc--Main (R6)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltclocal CuPvNusSba = workspace[game.Players.Localplayer.Name]
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltclocal sIECzkJdzw = CuPvNusSba:FindFirstChild("Humanoid")
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcCuPvNusSba.Archivable = true
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltclocal WwtTodwjwb = CuPvNusSba:Clone()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcWwtTodwjwb.Parent = CuPvNusSba
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcWwtTodwjwb.Name = "AsFatAsUrMother"
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcfor i,v in pairs(WwtTodwjwb:GetChildren())
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc		if v:IsA("BasePart") then v.Transparency = 1
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc					elseif v:IsA("Acessory") then v:Destroy()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc		end
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcend
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc--Noclip
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcgame:game:GetService("RunService").Stepped:Connect(function()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	sIECzkJdzw.Died:Connect(function()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc		return
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	end)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	for i, v in pairs(CuPvNusSba:GetChildren()) do
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc		if v:IsA("BasePart") then
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc			v.CanCollide = false
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc		end
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	end
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	--fricks cutelly
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcend)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcCuPvNusSba.Torso['Right Shoulder']:Destroy()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcCuPvNusSba.Torso['Left Shoulder']:Destroy()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcCuPvNusSba.Torso['Right Hip']:Destroy()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcCuPvNusSba.Torso['Left Hip']:Destroy()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcCuPvNusSba.sIECzkJdzwRootPart:Destroy()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcfunction tuFMPgaVhJ(P0)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	VvdgKaeTwm(CuPvNusSba[P0], WwtTodwjwb[P0])
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcend
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltctuFMPgaVhJ("Right Arm")
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltctuFMPgaVhJ("Left Arm")
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltctuFMPgaVhJ("Right Leg")
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltctuFMPgaVhJ("Left Leg")
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltctuFMPgaVhJ("Torso")
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc--Netless
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcgame:game:GetService("RunService").Heartbeat:Connect(function()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	for i, v in pairs(CuPvNusSba:GetChildren()) do
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc		if v:IsA("BasePart") then v.Velocity = _G.Velocity elseif v:IsA("Accessory") then v.Handle.Velocity = _G.Velocity end
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	end
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcend)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcgame.Players.LocalPlayer.CuPvNusSba = WwtTodwjwb
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcgame.Player.LocalPlauer.CuPvNusSba.sIECzkJdzw.Died:Connect(function()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	CuPvNusSba.sIECzkJdzw:ChangeState(15)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	game.Players.LocalPlayer.CuPvNusSba = workspace[game.Players.LocalPlayer.Name]
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc	WwtTodwjwb:Destroy()
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcend)
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltcworkspace:FindFirstChildOfClass("Camera").CameraSubject = WwtTodwjwb.sIECzkJdzw
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
nCNUsxeAJmXivZNPvclgezrSkbHBtDmCnCrsWhpEqDDcasGltc
